name: Certora Prover Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
      - run: npm install
      - run: |
          cd certora
          touch applyHarness.patch
          make munged
      - uses: Certora/certora-run-action@main
        with:
          configurations: |-
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule vp_change_in_balance_affect_power_DELEGATEE_all_others
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule vp_change_in_balance_affect_power_DELEGATEE_transfer_M
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule vp_change_in_balance_affect_power_DELEGATEE_stake_M
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule vp_change_in_balance_affect_power_DELEGATEE_redeem_M
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule vp_change_in_balance_affect_power_DELEGATEE_delegate_M
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule pp_change_in_balance_affect_power_DELEGATEE_all_others
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule pp_change_in_balance_affect_power_DELEGATEE_transfer_M
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule pp_change_in_balance_affect_power_DELEGATEE_stake_M
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule pp_change_in_balance_affect_power_DELEGATEE_redeem_M
            certora/conf/token-v3-delegate-HL-under-approx.conf --rule pp_change_in_balance_affect_power_DELEGATEE_delegate_M
            certora/conf/token-v3-delegate-HL.conf --rule vp_change_of_balance_affect_power_NON_DELEGATEE
            certora/conf/token-v3-delegate-HL.conf --rule pp_change_of_balance_affect_power_NON_DELEGATEE
            certora/conf/token-v3-delegate-HL.conf --rule mirror_votingDelegatee_correct mirror_propositionDelegatee_correct mirror_delegationMode_correct mirror_balance_correct inv_voting_power_correct inv_proposition_power_correct user_cant_voting_delegate_to_himself user_cant_proposition_delegate_to_himself no_function_changes_both_balance_and_delegation_state sum_all_voting_delegated_power_EQ_DelegatingVotingBal sum_all_proposition_delegated_power_EQ_DelegatingPropositionBal
            certora/conf/token-v3-delegate.conf
            certora/conf/allProps.conf --rule integrityOfSlashing --rule integrityOfStaking --rule previewStakeEquivalentStake --rule noStakingPostSlashingPeriod --rule noSlashingMoreThanMax --rule noRedeemOutOfUnstakeWindow --rule noEntryUntilSlashingSettled --rule integrityOfRedeem --rule cooldownCorrectness --rule airdropNotMutualized --rule integrityOfReturnFunds --rule slashAndReturnFundsOfZeroDoesntChangeExchangeRate
            certora/conf/allProps.conf --rule rewardsIncreaseForNonClaimFunctions
            certora/conf/allProps.conf --rule rewardsMonotonicallyIncrease
            certora/conf/allProps.conf --rule rewardsGetterEquivalentClaim
            certora/conf/allProps.conf --rule indexesMonotonicallyIncrease
            certora/conf/allProps.conf --rule exchangeRateNeverZero
            certora/conf/allProps.conf --rule totalSupplyDoesNotDropToZero
            certora/conf/allProps.conf --rule slashingIncreaseExchangeRate
            certora/conf/allProps.conf --rule returnFundsDecreaseExchangeRate
            certora/conf/propertiesWithSummarization.conf
            certora/conf/invariants.conf
            certora/conf/token-v3-general.conf --rule delegateCorrectness
            certora/conf/token-v3-general.conf --rule sumOfVBalancesCorrectness
            certora/conf/token-v3-general.conf --rule sumOfVBalancesCorrectness_onlyClaimRewardsAndRedeem
            certora/conf/token-v3-general.conf --rule sumOfVBalancesCorrectness_onlyClaimRewardsAndRedeemOnBehalf
            certora/conf/token-v3-general.conf --rule sumOfPBalancesCorrectness
            certora/conf/token-v3-general.conf --rule sumOfPBalancesCorrectness_onlyClaimRewardsAndRedeem
            certora/conf/token-v3-general.conf --rule sumOfPBalancesCorrectness_onlyClaimRewardsAndRedeemOnBehalf
            certora/conf/token-v3-general.conf --rule sumOfPBalancesCorrectness_onlyRedeem
            certora/conf/token-v3-general.conf --rule sumOfPBalancesCorrectness_onlyRedeemOnBehalf
            certora/conf/token-v3-general.conf --rule transferDoesntChangeDelegationMode
            certora/conf/token-v3-erc20.conf
            certora/conf/token-v3-community.conf
          solc-versions: 0.8.19
          solc-remove-version-prefix: "0."
          job-name: "Aave STK Governance"
          cli-version: 4.13.1
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
